[package]
name = 'AptosCoinV2Playground'
version = '1.0.0'

[addresses]
playground = "0xCAFE"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'
